source 'https://rubygems.org'
gem 'rails', '5.0.1'
gem 'bootstrap-sass'
gem 'bcrypt', '3.1.11'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'guard',                    '2.13.0'
  gem 'guard-minitest',           '2.4.4'  
  gem 'rails-controller-testing'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'pry-doc'  
end

group :development do
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end