# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provision "docker"
  config.vm.provision :docker_compose
  config.vm.network "forwarded_port", guest: 3000, host: 5005
  config.vm.network "private_network", ip: "192.168.33.11"
  config.vm.synced_folder "share/", "/vagrant/share", type: "rsync",
    rsync__args: %w(--verbose --archive --delete -z --copy-links --times),
    rsync__chown: false
  config.vm.provider "virtualbox" do |vb| 
    vb.memory = "4096"
  end
  config.vm.provision :shell, :path => "general.sh", privileged: true
  config.vm.provision :shell, :path => "ruby.sh", privileged: false
  config.vm.provision :shell, :path => "db_web_node.sh", privileged: true  
end