# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f86541de5de6805a5bd83806edfe2bf41f1e5ba3fdaf4891258dc4e21b58e74c97224cfe20df82acb692717ef82dfcf3dec179d0c7930edc52511580430845d0

test:
  secret_key_base: a90590c8768b4b14b319d467a0a7867aa545f6ddbaa616dbc59ef64d634a572c1930b60081e0a351add5e8ba04036c6b7863f28c780eedc099d0362401556150

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
